import type { Cliente, Moto, Recomendado } from "./schema";

export interface Galera {
  id_galera: number;
  nombre_cliente: string;
  repuestos: string;
  total_lps: number;
  trabajo_terminado: number;
}

const desktopApi =
  typeof window !== "undefined" ? window.motoPartsDesktop : undefined;

function desktopRequest<T>(operation: string, payload: unknown = {}): T {
  const response = desktopApi?.databaseRequest(operation, payload) as
    | T
    | { error: string };
  if (response && typeof response === "object" && "error" in response) {
    throw new Error(response.error);
  }
  return response as T;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function load<T>(key: string): T[] {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

function save<T>(key: string, data: T[]): void {
  localStorage.setItem(key, JSON.stringify(data));
}

function nextId(items: { [k: string]: unknown }[]): number {
  const ids = items.map((i) => Number(Object.values(i)[0]) || 0);
  return ids.length ? Math.max(...ids) + 1 : 1;
}

// ─── Seed ─────────────────────────────────────────────────────────────────────

const SEED_KEY = "motoparts_seeded_v2";

function seed() {
  if (localStorage.getItem(SEED_KEY)) return;

  const clientes: Cliente[] = [
    { id_cliente: 1, nombre: "Carlos Ramírez", telefono: "8888-1234" },
    { id_cliente: 2, nombre: "Ana Gómez", telefono: "7777-5678" },
    { id_cliente: 3, nombre: "Luis Herrera", telefono: "6666-9012" },
  ];

  const motos: Moto[] = [
    {
      id_moto: 1,
      id_cliente: 1,
      marca: "Bajaj",
      modelo: "NS200",
      anio: 2022,
      cilindraje: "200cc",
      tipo_motor: "Monocilíndrico 4T",
      refrigeracion: "Refrigeración por aceite",
      sistema_combustible: "Inyección electrónica",
      bloque_carter_motor: "Original Bajaj NS200",
      cilindro: "Original 200cc",
      culata: "Original DOHC",
      piston: "Original 72mm",
      aros_piston: "Original Bajaj",
      bulon_piston: "",
      biela: "Original",
      ciguenal: "Original NS200",
      arbol_levas: "Original DOHC",
      valvulas_admision_escape: "Original 4 válvulas",
      resortes_valvula: "",
      balancines: "",
      cadena_distribucion: "Original",
      tensor_distribucion: "Original",
      engranajes_distribucion: "",
      bomba_aceite: "Original",
      filtro_aceite: "Bajaj OEM",
      tapon_drenaje: "Original",
      carter_aceite: "Original",
      embrague: "Multidisco en baño de aceite",
      discos_embrague: "Original Bajaj",
      separadores_embrague: "Original",
      canasta_campana_embrague: "Original",
      plato_presion: "Original",
      resortes_embrague: "Original",
      caja_cambios: "6 velocidades",
      ejes_transmision: "Original",
      engranajes: "Original",
      selector_cambios: "Original",
      horquillas_selectoras: "",
      pinon_salida: "14T",
      cadena: "DID 520VX2 118 eslabones",
      corona_trasera: "42T",
      tensor_ajustadores_cadena: "Original",
      tanque_combustible: "12 litros",
      tapa_tanque: "Original",
      llave_combustible: "",
      bomba_gasolina: "Original eléctrica",
      filtro_combustible: "Original en bomba",
      carburador_inyector: "Bosch 32mm",
      cuerpo_aceleracion: "32mm",
      mangueras_combustible: "Original",
      regulador_presion: "Integrado en bomba",
      inyectores: "Bosch Original",
      flotador_sensor_nivel: "Original",
      filtro_aire: "Elemento filtrante original",
      caja_filtro_aire: "Original",
      conductos_admision: "Original",
      multiple_admision: "Original",
      escape: "Original Bajaj acero inox",
      multiple_escape: "Original",
      silenciador: "Original con catalizador",
      catalizador: "Original",
      sensor_oxigeno: "Bosch LSU 4.9",
      radiador: "",
      ventilador: "",
      bomba_agua: "",
      mangueras_refrigeracion: "",
      termostato: "",
      deposito_refrigerante: "",
      sensor_temperatura: "NTC en culata",
      aletas_refrigeracion: "",
      conductos_deflectores_aire: "",
      rin_delantero: "17 pulgadas aleación",
      neumatico_delantero: "MRF Nylogrip 100/80-17",
      camara_delantera: "",
      eje_delantero: "Original 17mm",
      rodamientos_delanteros: "SKF 6302",
      disco_freno_delantero: "260mm flotante",
      rin_trasero: "17 pulgadas aleación",
      neumatico_trasero: "MRF Nylogrip 130/70-17",
      camara_trasera: "",
      eje_trasero: "Original 20mm",
      rodamientos_traseros: "SKF 6303",
      corona: "42T acero",
      disco_freno_trasero: "230mm",
      tambor_freno_trasero: "",
      maneta_freno: "Original ajustable",
      bomba_freno: "Original Bajaj",
      deposito_liquido_freno: "Original",
      latiguillo_manguera_freno: "Original",
      pinza_freno: "Bybre 4 pistones delantera",
      pastillas_freno: "Sinterizadas Bybre",
      disco_freno: "260mm delantero",
      tambor: "",
      zapatas: "",
      chasis_bastidor: "Perimetral deltabox acero",
      subchasis: "Original aluminio",
      basculante: "Original aluminio",
      amortiguador_trasero: "Monoshock Nitrox",
      horquilla_delantera: "Telescópica invertida 37mm",
      barras_horquilla: "KYB 37mm",
      botellas_horquilla: "KYB",
      resortes_horquilla: "Original",
      tijas_superior_inferior: "Original aluminio",
      rodamientos_direccion: "SKF 32010",
      eje_direccion: "Original",
      manillar: "Semi-manillar de aluminio",
      punos: "Original Bajaj",
      acelerador: "Cable tipo pull",
      cable_sensor_acelerador: "Cable original 120cm",
      maneta_embrague: "Original ajustable",
      maneta_freno_control: "Original ajustable",
      pedal_cambio: "Original aluminio",
      pedal_freno: "Original",
      estriberas: "Original aluminio",
      soporte_estriberas: "Original",
      caballete_lateral: "Original acero",
      caballete_central: "",
      bateria: "Yuasa YTZ7S 12V 6Ah",
      alternador_estator: "Original 150W",
      rotor_volante_magnetico: "Original",
      regulador_rectificador: "Original Bajaj",
      motor_arranque: "Original Minda 0.5kW",
      rele_arranque: "Original",
      solenoide: "Original",
      ecu_cdi: "Bosch ME17",
      bobina_encendido: "Original",
      bujia: "NGK DCPR8E",
      cableado: "Original Bajaj",
      fusibles: "Original 15A/20A",
      reles: "Original",
      interruptor_encendido: "Original",
      interruptor_luces: "Original izquierdo",
      interruptor_intermitentes: "Original",
      claxon: "Original Bajaj",
      sensores: "TPS, MAP, CKP, CMP",
      faro_delantero: "Proyector LED",
      luz_posicion: "LED",
      luz_trasera: "LED",
      luz_freno: "LED integrado",
      intermitentes: "LED ámbar",
      bombillas_modulos_led: "Módulo LED original",
      luz_matricula: "LED",
      deposito_tanque: "12L plástico",
      asiento: "Original monobloque",
      guardabarros_delantero: "Original plástico",
      guardabarros_trasero: "Original plástico",
      carenados: "Semi-carenado ABS",
      paneles_laterales: "ABS original",
      colin: "Original",
      cupula_parabrisas: "",
      parrilla_portaequipaje: "",
      soporte_matricula: "Original",
      velocimetro: "Digital original",
      tacometro: "Digital integrado",
      odometro: "Digital",
      indicador_combustible: "Digital 4 barras",
      indicador_temperatura: "Testigo digital",
      pantalla_panel_instrumentos: "LCD retroiluminado",
      testigo_aceite: "Original",
      testigo_motor: "Original MIL",
      testigo_direccionales: "Original",
      testigo_luces_altas: "Original",
      testigo_neutro: "Original",
      tornillos: "Kit original M6/M8",
      tuercas: "Original inox",
      arandelas: "Original",
      pasadores: "Original",
      clips: "Original",
      seguros: "Original",
      abrazaderas: "Original",
      retenes: "Original aceite 37mm",
      juntas: "Kit juntas motor original",
      o_rings: "Original NBR",
      rodamientos: "SKF varios",
      bujes: "Original bronce",
      resortes: "Original varios",
      cables: "Kit cables original",
      mangueras: "Original caucho",
    },
    {
      id_moto: 2,
      id_cliente: 2,
      marca: "Honda",
      modelo: "CB190R",
      anio: 2021,
      cilindraje: "184cc",
      tipo_motor: "Monocilíndrico 4T SOHC",
      refrigeracion: "Refrigeración por aire",
      sistema_combustible: "Carburador",
      bloque_carter_motor: "Original Honda",
      cilindro: "Original 63mm",
      culata: "SOHC 2 válvulas",
      piston: "Original 63mm",
      aros_piston: "Original Honda",
      bulon_piston: "Original 14mm",
      biela: "Original",
      ciguenal: "Original Honda",
      arbol_levas: "SOHC cadena",
      valvulas_admision_escape: "Original 2V",
      resortes_valvula: "Original",
      balancines: "Original",
      cadena_distribucion: "Original Honda",
      tensor_distribucion: "Original automático",
      engranajes_distribucion: "Original",
      bomba_aceite: "Original trócola",
      filtro_aceite: "Honda OEM 15410-MCJ-505",
      tapon_drenaje: "Original M12",
      carter_aceite: "Original aluminio",
      embrague: "Multidisco húmedo",
      discos_embrague: "Original Honda 5 discos",
      separadores_embrague: "Original 5 piezas",
      canasta_campana_embrague: "Original",
      plato_presion: "Original",
      resortes_embrague: "Original 5 resortes",
      caja_cambios: "5 velocidades",
      ejes_transmision: "Original",
      engranajes: "Original",
      selector_cambios: "Original",
      horquillas_selectoras: "Original",
      pinon_salida: "15T",
      cadena: "DID 428VX 124 eslabones",
      corona_trasera: "38T",
      tensor_ajustadores_cadena: "Original",
      tanque_combustible: "13.7 litros",
      tapa_tanque: "Original con llave",
      llave_combustible: "Vacío/Reserva/Off",
      bomba_gasolina: "",
      filtro_combustible: "Inline original",
      carburador_inyector: "Keihin CV 26mm",
      cuerpo_aceleracion: "26mm",
      mangueras_combustible: "Original",
      regulador_presion: "",
      inyectores: "",
      flotador_sensor_nivel: "Flotador original",
      filtro_aire: "Esponja original",
      caja_filtro_aire: "Original plástico",
      conductos_admision: "Original",
      multiple_admision: "Original aluminio",
      escape: "Original Honda cromado",
      multiple_escape: "Original",
      silenciador: "Original cromado",
      catalizador: "",
      sensor_oxigeno: "",
      radiador: "",
      ventilador: "",
      bomba_agua: "",
      mangueras_refrigeracion: "",
      termostato: "",
      deposito_refrigerante: "",
      sensor_temperatura: "",
      aletas_refrigeracion: "Aletas fundidas en cilindro",
      conductos_deflectores_aire: "Original",
      rin_delantero: "17 pulgadas acero",
      neumatico_delantero: "IRC NR73 80/100-17",
      camara_delantera: "IRC",
      eje_delantero: "Original 12mm",
      rodamientos_delanteros: "NSK 6301",
      disco_freno_delantero: "240mm disco simple",
      rin_trasero: "17 pulgadas acero",
      neumatico_trasero: "IRC NR73 100/80-17",
      camara_trasera: "IRC",
      eje_trasero: "Original 20mm",
      rodamientos_traseros: "NSK 6302",
      corona: "38T acero",
      disco_freno_trasero: "",
      tambor_freno_trasero: "Tambor 130mm",
      maneta_freno: "Original Honda",
      bomba_freno: "Original hidráulica delantera",
      deposito_liquido_freno: "Original",
      latiguillo_manguera_freno: "Original",
      pinza_freno: "Nissin 2 pistones",
      pastillas_freno: "Sinterizadas OEM",
      disco_freno: "240mm",
      tambor: "130mm trasero",
      zapatas: "Original Honda",
      chasis_bastidor: "Doble cuna acero",
      subchasis: "Original acero",
      basculante: "Original acero",
      amortiguador_trasero: "Doble amortiguador",
      horquilla_delantera: "Telescópica convencional 33mm",
      barras_horquilla: "Original 33mm",
      botellas_horquilla: "Original",
      resortes_horquilla: "Original",
      tijas_superior_inferior: "Original acero",
      rodamientos_direccion: "SKF 30204",
      eje_direccion: "Original",
      manillar: "Tubo acero",
      punos: "Original Honda",
      acelerador: "Cable tipo push-pull",
      cable_sensor_acelerador: "Cable original 90cm",
      maneta_embrague: "Original",
      maneta_freno_control: "Original",
      pedal_cambio: "Original acero",
      pedal_freno: "Original",
      estriberas: "Original acero",
      soporte_estriberas: "Original",
      caballete_lateral: "Original acero",
      caballete_central: "Original acero",
      bateria: "Yuasa YTX7L-BS 12V 6Ah",
      alternador_estator: "Original 100W",
      rotor_volante_magnetico: "Original",
      regulador_rectificador: "Original Honda",
      motor_arranque: "Original 0.4kW",
      rele_arranque: "Original",
      solenoide: "Original",
      ecu_cdi: "CDI Digital Honda",
      bobina_encendido: "Original",
      bujia: "NGK CPR8EA-9",
      cableado: "Original Honda",
      fusibles: "Original 10A/15A",
      reles: "Original",
      interruptor_encendido: "Original",
      interruptor_luces: "Original",
      interruptor_intermitentes: "Original",
      claxon: "Original Honda",
      sensores: "CKP",
      faro_delantero: "Halógeno H4 35/35W",
      luz_posicion: "5W",
      luz_trasera: "Incandescente 10W",
      luz_freno: "21W",
      intermitentes: "21W ámbar",
      bombillas_modulos_led: "",
      luz_matricula: "5W",
      deposito_tanque: "13.7L acero",
      asiento: "Original monobloque",
      guardabarros_delantero: "Original plástico",
      guardabarros_trasero: "Original plástico",
      carenados: "",
      paneles_laterales: "Original plástico",
      colin: "Original",
      cupula_parabrisas: "",
      parrilla_portaequipaje: "",
      soporte_matricula: "Original",
      velocimetro: "Analógico",
      tacometro: "",
      odometro: "Mecánico integrado",
      indicador_combustible: "Llave de combustible manual",
      indicador_temperatura: "",
      pantalla_panel_instrumentos: "Analógico",
      testigo_aceite: "Original",
      testigo_motor: "",
      testigo_direccionales: "Original",
      testigo_luces_altas: "Original",
      testigo_neutro: "Original",
      tornillos: "Kit M6/M8 acero",
      tuercas: "Original",
      arandelas: "Original",
      pasadores: "Original",
      clips: "Original",
      seguros: "Original",
      abrazaderas: "Original",
      retenes: "Original 33mm horquilla",
      juntas: "Kit juntas OEM",
      o_rings: "Original NBR",
      rodamientos: "NSK varios",
      bujes: "Original",
      resortes: "Original",
      cables: "Kit cables OEM",
      mangueras: "Original",
    },
    {
      id_moto: 3,
      id_cliente: null,
      marca: "Yamaha",
      modelo: "FZ-S",
      anio: 2020,
      cilindraje: "149cc",
      tipo_motor: "Monocilíndrico 4T SOHC",
      refrigeracion: "Refrigeración por aire",
      sistema_combustible: "Inyección electrónica",
      bloque_carter_motor: "",
      cilindro: "",
      culata: "",
      piston: "Original 57.3mm",
      aros_piston: "",
      bulon_piston: "",
      biela: "",
      ciguenal: "Original Yamaha",
      arbol_levas: "",
      valvulas_admision_escape: "",
      resortes_valvula: "",
      balancines: "",
      cadena_distribucion: "",
      tensor_distribucion: "",
      engranajes_distribucion: "",
      bomba_aceite: "",
      filtro_aceite: "Yamaha OEM",
      tapon_drenaje: "",
      carter_aceite: "",
      embrague: "Multidisco húmedo",
      discos_embrague: "",
      separadores_embrague: "",
      canasta_campana_embrague: "",
      plato_presion: "",
      resortes_embrague: "",
      caja_cambios: "5 velocidades",
      ejes_transmision: "",
      engranajes: "",
      selector_cambios: "",
      horquillas_selectoras: "",
      pinon_salida: "14T",
      cadena: "DID 428DS 120 eslabones",
      corona_trasera: "40T",
      tensor_ajustadores_cadena: "",
      tanque_combustible: "12 litros",
      tapa_tanque: "",
      llave_combustible: "",
      bomba_gasolina: "Original eléctrica",
      filtro_combustible: "",
      carburador_inyector: "Yamaha FI 26mm",
      cuerpo_aceleracion: "",
      mangueras_combustible: "",
      regulador_presion: "",
      inyectores: "Denso original",
      flotador_sensor_nivel: "",
      filtro_aire: "Elemento filtrante original",
      caja_filtro_aire: "",
      conductos_admision: "",
      multiple_admision: "",
      escape: "Original Yamaha",
      multiple_escape: "",
      silenciador: "Original",
      catalizador: "",
      sensor_oxigeno: "",
      radiador: "",
      ventilador: "",
      bomba_agua: "",
      mangueras_refrigeracion: "",
      termostato: "",
      deposito_refrigerante: "",
      sensor_temperatura: "",
      aletas_refrigeracion: "",
      conductos_deflectores_aire: "",
      rin_delantero: "17 pulgadas aleación",
      neumatico_delantero: "MRF Revz 100/80-17",
      camara_delantera: "",
      eje_delantero: "",
      rodamientos_delanteros: "",
      disco_freno_delantero: "282mm",
      rin_trasero: "17 pulgadas aleación",
      neumatico_trasero: "MRF Revz 140/60-17",
      camara_trasera: "",
      eje_trasero: "",
      rodamientos_traseros: "",
      corona: "40T",
      disco_freno_trasero: "220mm",
      tambor_freno_trasero: "",
      maneta_freno: "",
      bomba_freno: "",
      deposito_liquido_freno: "",
      latiguillo_manguera_freno: "",
      pinza_freno: "",
      pastillas_freno: "",
      disco_freno: "",
      tambor: "",
      zapatas: "",
      chasis_bastidor: "Doble viga diamante",
      subchasis: "",
      basculante: "",
      amortiguador_trasero: "Monoshock",
      horquilla_delantera: "Telescópica 41mm",
      barras_horquilla: "",
      botellas_horquilla: "",
      resortes_horquilla: "",
      tijas_superior_inferior: "",
      rodamientos_direccion: "",
      eje_direccion: "",
      manillar: "Semi-manillar",
      punos: "",
      acelerador: "",
      cable_sensor_acelerador: "",
      maneta_embrague: "",
      maneta_freno_control: "",
      pedal_cambio: "",
      pedal_freno: "",
      estriberas: "",
      soporte_estriberas: "",
      caballete_lateral: "Original",
      caballete_central: "",
      bateria: "Yuasa YTZ5S 12V 4Ah",
      alternador_estator: "",
      rotor_volante_magnetico: "",
      regulador_rectificador: "",
      motor_arranque: "",
      rele_arranque: "",
      solenoide: "",
      ecu_cdi: "Yamaha FI ECU",
      bobina_encendido: "",
      bujia: "NGK CR7E",
      cableado: "",
      fusibles: "",
      reles: "",
      interruptor_encendido: "",
      interruptor_luces: "",
      interruptor_intermitentes: "",
      claxon: "",
      sensores: "TPS, MAP",
      faro_delantero: "LED proyector",
      luz_posicion: "LED",
      luz_trasera: "LED",
      luz_freno: "LED",
      intermitentes: "LED ámbar",
      bombillas_modulos_led: "",
      luz_matricula: "LED",
      deposito_tanque: "12L plástico",
      asiento: "Original",
      guardabarros_delantero: "Original",
      guardabarros_trasero: "Original",
      carenados: "Semi-carenado",
      paneles_laterales: "",
      colin: "",
      cupula_parabrisas: "",
      parrilla_portaequipaje: "",
      soporte_matricula: "",
      velocimetro: "Digital LCD",
      tacometro: "Digital",
      odometro: "Digital",
      indicador_combustible: "Digital barras",
      indicador_temperatura: "",
      pantalla_panel_instrumentos: "LCD color",
      testigo_aceite: "",
      testigo_motor: "FI testigo",
      testigo_direccionales: "",
      testigo_luces_altas: "",
      testigo_neutro: "",
      tornillos: "",
      tuercas: "",
      arandelas: "",
      pasadores: "",
      clips: "",
      seguros: "",
      abrazaderas: "",
      retenes: "",
      juntas: "",
      o_rings: "",
      rodamientos: "",
      bujes: "",
      resortes: "",
      cables: "",
      mangueras: "",
    },
  ];

  const recomendados: Recomendado[] = [
    {
      id_recomendado: 1,
      marca: "Bajaj",
      modelo: "NS200",
      anio: null,
      cilindraje: "200cc",
      tipo_motor: "Monocilíndrico 4T DOHC",
      refrigeracion: "Refrigeración por aceite",
      sistema_combustible: "Inyección electrónica",
      bloque_carter_motor: "Original Bajaj",
      posible_adaptacion_bloque_carter_motor: "—",
      cilindro: "Original 72mm",
      posible_adaptacion_cilindro: "—",
      culata: "Original DOHC",
      posible_adaptacion_culata: "—",
      piston: "Original 72mm",
      posible_adaptacion_piston: "Piston Wiseco 72mm",
      aros_piston: "Original Bajaj",
      posible_adaptacion_aros_piston: "Aros oversize 0.25mm",
      bulon_piston: "Original 16mm",
      posible_adaptacion_bulon_piston: "—",
      biela: "Original",
      posible_adaptacion_biela: "—",
      ciguenal: "Original NS200",
      posible_adaptacion_ciguenal: "—",
      arbol_levas: "Original DOHC",
      posible_adaptacion_arbol_levas: "—",
      valvulas_admision_escape: "Original 4 válvulas",
      posible_adaptacion_valvulas_admision_escape: "Válvulas Kibblewhite",
      resortes_valvula: "Original",
      posible_adaptacion_resortes_valvula: "—",
      balancines: "Original",
      posible_adaptacion_balancines: "—",
      cadena_distribucion: "DID SCA0412",
      posible_adaptacion_cadena_distribucion: "RK SCA428",
      tensor_distribucion: "Original automático",
      posible_adaptacion_tensor_distribucion: "—",
      engranajes_distribucion: "Original",
      posible_adaptacion_engranajes_distribucion: "—",
      bomba_aceite: "Original trócola",
      posible_adaptacion_bomba_aceite: "—",
      filtro_aceite: "Bajaj OEM",
      posible_adaptacion_filtro_aceite: "Hiflofiltro HF163",
      tapon_drenaje: "Original M12x1.5",
      posible_adaptacion_tapon_drenaje: "Tapón magnético universal",
      carter_aceite: "Original",
      posible_adaptacion_carter_aceite: "—",
      embrague: "Multidisco en baño de aceite",
      posible_adaptacion_embrague: "—",
      discos_embrague: "Original Bajaj 6 discos",
      posible_adaptacion_discos_embrague: "EBC CK series",
      separadores_embrague: "Original",
      posible_adaptacion_separadores_embrague: "—",
      canasta_campana_embrague: "Original aluminio",
      posible_adaptacion_canasta_campana_embrague: "—",
      plato_presion: "Original",
      posible_adaptacion_plato_presion: "—",
      resortes_embrague: "Original",
      posible_adaptacion_resortes_embrague: "EBC CSK series",
      caja_cambios: "6 velocidades retorno",
      posible_adaptacion_caja_cambios: "—",
      ejes_transmision: "Original",
      posible_adaptacion_ejes_transmision: "—",
      engranajes: "Original",
      posible_adaptacion_engranajes: "—",
      selector_cambios: "Original",
      posible_adaptacion_selector_cambios: "—",
      horquillas_selectoras: "Original",
      posible_adaptacion_horquillas_selectoras: "—",
      pinon_salida: "14T original",
      posible_adaptacion_pinon_salida: "JT Sprockets JTF1304.14",
      cadena: "DID 520VX2 108-118 eslabones",
      posible_adaptacion_cadena: "RK 520MXZ4 118 eslabones",
      corona_trasera: "42T acero original",
      posible_adaptacion_corona_trasera: "JT Sprockets JTR820.42",
      tensor_ajustadores_cadena: "Original",
      posible_adaptacion_tensor_ajustadores_cadena: "—",
      tanque_combustible: "12 litros original",
      posible_adaptacion_tanque_combustible: "—",
      tapa_tanque: "Original",
      posible_adaptacion_tapa_tanque: "Rizoma universal",
      llave_combustible: "",
      posible_adaptacion_llave_combustible: "",
      bomba_gasolina: "Bosch eléctrica original",
      posible_adaptacion_bomba_gasolina: "Bosch 0580254044",
      filtro_combustible: "Integrado en bomba",
      posible_adaptacion_filtro_combustible: "Filtro inline K&N KF-1004",
      carburador_inyector: "Bosch 32mm inyección",
      posible_adaptacion_carburador_inyector: "Cuerpo aceleración 35mm aftermarket",
      cuerpo_aceleracion: "32mm original",
      posible_adaptacion_cuerpo_aceleracion: "—",
      mangueras_combustible: "Original silicona",
      posible_adaptacion_mangueras_combustible: "Kit mangueras Gates",
      regulador_presion: "Integrado en bomba",
      posible_adaptacion_regulador_presion: "—",
      inyectores: "Bosch original 150cc/min",
      posible_adaptacion_inyectores: "Inyector 200cc/min compatible",
      flotador_sensor_nivel: "Original",
      posible_adaptacion_flotador_sensor_nivel: "—",
      filtro_aire: "Original elemento filtrante",
      posible_adaptacion_filtro_aire: "K&N RC-2370 sport air filter",
      caja_filtro_aire: "Original plástico",
      posible_adaptacion_caja_filtro_aire: "—",
      conductos_admision: "Original",
      posible_adaptacion_conductos_admision: "—",
      multiple_admision: "Original aluminio",
      posible_adaptacion_multiple_admision: "—",
      escape: "Original inoxidable",
      posible_adaptacion_escape: "Akrapovič Evolution compatible",
      multiple_escape: "Original",
      posible_adaptacion_multiple_escape: "—",
      silenciador: "Original con catalizador",
      posible_adaptacion_silenciador: "Arrow Pro-Race silencer",
      catalizador: "Original",
      posible_adaptacion_catalizador: "—",
      sensor_oxigeno: "Bosch LSU 4.9",
      posible_adaptacion_sensor_oxigeno: "NGK OZA603-H2",
      radiador: "",
      posible_adaptacion_radiador: "",
      ventilador: "",
      posible_adaptacion_ventilador: "",
      bomba_agua: "",
      posible_adaptacion_bomba_agua: "",
      mangueras_refrigeracion: "",
      posible_adaptacion_mangueras_refrigeracion: "",
      termostato: "",
      posible_adaptacion_termostato: "",
      deposito_refrigerante: "",
      posible_adaptacion_deposito_refrigerante: "",
      sensor_temperatura: "NTC en culata",
      posible_adaptacion_sensor_temperatura: "Sensor NTC compatible",
      aletas_refrigeracion: "",
      posible_adaptacion_aletas_refrigeracion: "",
      conductos_deflectores_aire: "",
      posible_adaptacion_conductos_deflectores_aire: "",
      rin_delantero: "17\" aleación original",
      posible_adaptacion_rin_delantero: "Excel Takasago 17\"",
      neumatico_delantero: "MRF Nylogrip 100/80-17",
      posible_adaptacion_neumatico_delantero: "Michelin Pilot Street 2 100/80-17",
      camara_delantera: "Sin cámara (sin cámara)",
      posible_adaptacion_camara_delantera: "—",
      eje_delantero: "Original 17mm",
      posible_adaptacion_eje_delantero: "—",
      rodamientos_delanteros: "SKF 6302-2RS",
      posible_adaptacion_rodamientos_delanteros: "FAG 6302-2RSR",
      disco_freno_delantero: "260mm flotante original",
      posible_adaptacion_disco_freno_delantero: "Galfer DF308CRT 260mm",
      rin_trasero: "17\" aleación original",
      posible_adaptacion_rin_trasero: "Excel Takasago 17\"",
      neumatico_trasero: "MRF Nylogrip 130/70-17",
      posible_adaptacion_neumatico_trasero: "Michelin Pilot Street 2 130/70-17",
      camara_trasera: "Sin cámara",
      posible_adaptacion_camara_trasera: "—",
      eje_trasero: "Original 20mm",
      posible_adaptacion_eje_trasero: "—",
      rodamientos_traseros: "SKF 6303-2RS",
      posible_adaptacion_rodamientos_traseros: "FAG 6303-2RSR",
      corona: "42T acero original",
      posible_adaptacion_corona: "JT Sprockets JTR820.42 acero / Sunstar aluminio 42T",
      disco_freno_trasero: "230mm original",
      posible_adaptacion_disco_freno_trasero: "Galfer 230mm standard",
      tambor_freno_trasero: "",
      posible_adaptacion_tambor_freno_trasero: "",
      maneta_freno: "Original ajustable",
      posible_adaptacion_maneta_freno: "Rizoma LBJ205B ajustable",
      bomba_freno: "Original Bybre",
      posible_adaptacion_bomba_freno: "Brembo PR 15x18",
      deposito_liquido_freno: "Original",
      posible_adaptacion_deposito_liquido_freno: "Brembo depósito externo",
      latiguillo_manguera_freno: "Original",
      posible_adaptacion_latiguillo_manguera_freno: "Galfer acero trenzado",
      pinza_freno: "Bybre 4P delantera",
      posible_adaptacion_pinza_freno: "Brembo M4 65mm",
      pastillas_freno: "Sinterizadas Bybre OEM",
      posible_adaptacion_pastillas_freno: "EBC FA413HH sinterizadas racing",
      disco_freno: "260mm",
      posible_adaptacion_disco_freno: "Galfer DF308CRT",
      tambor: "",
      posible_adaptacion_tambor: "",
      zapatas: "",
      posible_adaptacion_zapatas: "",
      chasis_bastidor: "Perimetral deltabox acero",
      posible_adaptacion_chasis_bastidor: "—",
      subchasis: "Aluminio original",
      posible_adaptacion_subchasis: "—",
      basculante: "Aluminio original",
      posible_adaptacion_basculante: "—",
      amortiguador_trasero: "Nitrox monoshock",
      posible_adaptacion_amortiguador_trasero: "YSS MZ456-310TR-09",
      horquilla_delantera: "KYB invertida 37mm",
      posible_adaptacion_horquilla_delantera: "—",
      barras_horquilla: "KYB 37mm originales",
      posible_adaptacion_barras_horquilla: "—",
      botellas_horquilla: "KYB originales",
      posible_adaptacion_botellas_horquilla: "—",
      resortes_horquilla: "Original KYB",
      posible_adaptacion_resortes_horquilla: "Hyperpro RSC34-0095",
      tijas_superior_inferior: "Aluminio original",
      posible_adaptacion_tijas_superior_inferior: "—",
      rodamientos_direccion: "SKF 32010-X",
      posible_adaptacion_rodamientos_direccion: "FAG 32010-X",
      eje_direccion: "Original",
      posible_adaptacion_eje_direccion: "—",
      manillar: "Semi-manillar aluminio",
      posible_adaptacion_manillar: "Renthal Fatbar 34mm",
      punos: "Original Bajaj",
      posible_adaptacion_punos: "Progrip 717 Ø22mm",
      acelerador: "Cable pull original",
      posible_adaptacion_acelerador: "Domino kit acelerador",
      cable_sensor_acelerador: "Cable original 120cm",
      posible_adaptacion_cable_sensor_acelerador: "Cable aftermarket 120cm",
      maneta_embrague: "Original ajustable",
      posible_adaptacion_maneta_embrague: "Rizoma LBJ205B",
      maneta_freno_control: "Original ajustable",
      posible_adaptacion_maneta_freno_control: "Rizoma LBJ205B",
      pedal_cambio: "Aluminio original",
      posible_adaptacion_pedal_cambio: "Valtermo aluminio CNC",
      pedal_freno: "Original",
      posible_adaptacion_pedal_freno: "—",
      estriberas: "Aluminio original",
      posible_adaptacion_estriberas: "Valtermo MX aluminio",
      soporte_estriberas: "Original",
      posible_adaptacion_soporte_estriberas: "—",
      caballete_lateral: "Acero original",
      posible_adaptacion_caballete_lateral: "—",
      caballete_central: "",
      posible_adaptacion_caballete_central: "",
      bateria: "Yuasa YTZ7S 12V 6Ah",
      posible_adaptacion_bateria: "Motobatt MBTZ7S",
      alternador_estator: "Original 150W",
      posible_adaptacion_alternador_estator: "—",
      rotor_volante_magnetico: "Original",
      posible_adaptacion_rotor_volante_magnetico: "—",
      regulador_rectificador: "Original Bajaj",
      posible_adaptacion_regulador_rectificador: "Moose Racing 2112-1017",
      motor_arranque: "Minda 0.5kW",
      posible_adaptacion_motor_arranque: "—",
      rele_arranque: "Original",
      posible_adaptacion_rele_arranque: "Relé universal 12V 30A",
      solenoide: "Original",
      posible_adaptacion_solenoide: "—",
      ecu_cdi: "Bosch ME17",
      posible_adaptacion_ecu_cdi: "—",
      bobina_encendido: "Original",
      posible_adaptacion_bobina_encendido: "Dyna DC6-1",
      bujia: "NGK DCPR8E",
      posible_adaptacion_bujia: "Iridium NGK DCPR8EIX",
      cableado: "Original Bajaj",
      posible_adaptacion_cableado: "—",
      fusibles: "Original 15A/20A",
      posible_adaptacion_fusibles: "Kit fusibles ATC universales",
      reles: "Original",
      posible_adaptacion_reles: "—",
      interruptor_encendido: "Original",
      posible_adaptacion_interruptor_encendido: "—",
      interruptor_luces: "Original",
      posible_adaptacion_interruptor_luces: "—",
      interruptor_intermitentes: "Original",
      posible_adaptacion_interruptor_intermitentes: "—",
      claxon: "Original Bajaj",
      posible_adaptacion_claxon: "FIAMM HO2/HP2 120dB",
      sensores: "TPS, MAP, CKP, CMP",
      posible_adaptacion_sensores: "—",
      faro_delantero: "LED proyector original",
      posible_adaptacion_faro_delantero: "—",
      luz_posicion: "LED original",
      posible_adaptacion_luz_posicion: "—",
      luz_trasera: "LED original",
      posible_adaptacion_luz_trasera: "—",
      luz_freno: "LED integrado",
      posible_adaptacion_luz_freno: "—",
      intermitentes: "LED ámbar original",
      posible_adaptacion_intermitentes: "Rizoma Freccia LED",
      bombillas_modulos_led: "Módulo LED original",
      posible_adaptacion_bombillas_modulos_led: "—",
      luz_matricula: "LED original",
      posible_adaptacion_luz_matricula: "—",
      deposito_tanque: "12L plástico",
      posible_adaptacion_deposito_tanque: "—",
      asiento: "Original monobloque",
      posible_adaptacion_asiento: "Asiento sport aftermarket",
      guardabarros_delantero: "Original plástico",
      posible_adaptacion_guardabarros_delantero: "Puig 5872N carbono look",
      guardabarros_trasero: "Original plástico",
      posible_adaptacion_guardabarros_trasero: "—",
      carenados: "Semi-carenado ABS",
      posible_adaptacion_carenados: "—",
      paneles_laterales: "ABS original",
      posible_adaptacion_paneles_laterales: "—",
      colin: "Original",
      posible_adaptacion_colin: "—",
      cupula_parabrisas: "",
      posible_adaptacion_cupula_parabrisas: "Puig Sport windscreen",
      parrilla_portaequipaje: "",
      posible_adaptacion_parrilla_portaequipaje: "",
      soporte_matricula: "Original",
      posible_adaptacion_soporte_matricula: "Eliminador matrícula Barracuda",
      velocimetro: "Digital LCD original",
      posible_adaptacion_velocimetro: "—",
      tacometro: "Digital integrado",
      posible_adaptacion_tacometro: "—",
      odometro: "Digital",
      posible_adaptacion_odometro: "—",
      indicador_combustible: "Digital 4 barras",
      posible_adaptacion_indicador_combustible: "—",
      indicador_temperatura: "Testigo digital",
      posible_adaptacion_indicador_temperatura: "—",
      pantalla_panel_instrumentos: "LCD retroiluminado",
      posible_adaptacion_pantalla_panel_instrumentos: "—",
      testigo_aceite: "Original",
      posible_adaptacion_testigo_aceite: "—",
      testigo_motor: "MIL original",
      posible_adaptacion_testigo_motor: "—",
      testigo_direccionales: "Original",
      posible_adaptacion_testigo_direccionales: "—",
      testigo_luces_altas: "Original",
      posible_adaptacion_testigo_luces_altas: "—",
      testigo_neutro: "Original",
      posible_adaptacion_testigo_neutro: "—",
      tornillos: "Kit M6/M8 acero",
      posible_adaptacion_tornillos: "Kit titanio M6/M8 Vortex",
      tuercas: "Original inox",
      posible_adaptacion_tuercas: "Tuercas nyloc inox",
      arandelas: "Original",
      posible_adaptacion_arandelas: "—",
      pasadores: "Original",
      posible_adaptacion_pasadores: "—",
      clips: "Original",
      posible_adaptacion_clips: "—",
      seguros: "Original",
      posible_adaptacion_seguros: "—",
      abrazaderas: "Original",
      posible_adaptacion_abrazaderas: "Abrazaderas acero inox",
      retenes: "Original aceite 37mm",
      posible_adaptacion_retenes: "Athena horquilla 37mm",
      juntas: "Kit juntas motor original",
      posible_adaptacion_juntas: "Athena kit juntas completo",
      o_rings: "Original NBR",
      posible_adaptacion_o_rings: "O-ring kit Viton compatible",
      rodamientos: "SKF varios",
      posible_adaptacion_rodamientos: "FAG equivalentes",
      bujes: "Original bronce",
      posible_adaptacion_bujes: "DU bronce/teflón",
      resortes: "Original varios",
      posible_adaptacion_resortes: "—",
      cables: "Kit cables original",
      posible_adaptacion_cables: "Venhill kit cables",
      mangueras: "Original caucho",
      posible_adaptacion_mangueras: "Kit mangueras silicona",
    },
    {
      id_recomendado: 2,
      marca: "Honda",
      modelo: "CB190R",
      anio: null,
      cilindraje: "184cc",
      tipo_motor: "Monocilíndrico SOHC",
      refrigeracion: "Refrigeración por aire",
      sistema_combustible: "Carburador",
      bloque_carter_motor: "Original Honda",
      posible_adaptacion_bloque_carter_motor: "—",
      cilindro: "Original 63mm",
      posible_adaptacion_cilindro: "Cilindro oversize Vertex",
      culata: "SOHC 2 válvulas original",
      posible_adaptacion_culata: "—",
      piston: "Original 63mm",
      posible_adaptacion_piston: "Wiseco 63mm forjado",
      aros_piston: "Original Honda",
      posible_adaptacion_aros_piston: "Aros oversize 0.5mm",
      bulon_piston: "Original 14mm",
      posible_adaptacion_bulon_piston: "—",
      biela: "Original",
      posible_adaptacion_biela: "—",
      ciguenal: "Original Honda",
      posible_adaptacion_ciguenal: "—",
      arbol_levas: "SOHC cadena",
      posible_adaptacion_arbol_levas: "—",
      valvulas_admision_escape: "Original 2V",
      posible_adaptacion_valvulas_admision_escape: "Kibblewhite equivalente",
      resortes_valvula: "Original",
      posible_adaptacion_resortes_valvula: "—",
      balancines: "Original",
      posible_adaptacion_balancines: "—",
      cadena_distribucion: "RK 219H",
      posible_adaptacion_cadena_distribucion: "DID equivalente",
      tensor_distribucion: "Original automático",
      posible_adaptacion_tensor_distribucion: "—",
      engranajes_distribucion: "Original",
      posible_adaptacion_engranajes_distribucion: "—",
      bomba_aceite: "Original trócola",
      posible_adaptacion_bomba_aceite: "—",
      filtro_aceite: "Honda OEM 15410-MCJ-505",
      posible_adaptacion_filtro_aceite: "Hiflofiltro HF111",
      tapon_drenaje: "Original M12x1.25",
      posible_adaptacion_tapon_drenaje: "Tapón magnético Dr.Pulley",
      carter_aceite: "Original aluminio",
      posible_adaptacion_carter_aceite: "—",
      embrague: "Multidisco húmedo 5 discos",
      posible_adaptacion_embrague: "—",
      discos_embrague: "Original Honda 5 discos",
      posible_adaptacion_discos_embrague: "EBC CK series Honda",
      separadores_embrague: "Original",
      posible_adaptacion_separadores_embrague: "—",
      canasta_campana_embrague: "Original",
      posible_adaptacion_canasta_campana_embrague: "—",
      plato_presion: "Original",
      posible_adaptacion_plato_presion: "—",
      resortes_embrague: "Original",
      posible_adaptacion_resortes_embrague: "EBC CSK Honda",
      caja_cambios: "5 velocidades retorno",
      posible_adaptacion_caja_cambios: "—",
      ejes_transmision: "Original",
      posible_adaptacion_ejes_transmision: "—",
      engranajes: "Original",
      posible_adaptacion_engranajes: "—",
      selector_cambios: "Original",
      posible_adaptacion_selector_cambios: "—",
      horquillas_selectoras: "Original",
      posible_adaptacion_horquillas_selectoras: "—",
      pinon_salida: "15T original",
      posible_adaptacion_pinon_salida: "JT Sprockets JTF284",
      cadena: "DID 428VX 124 eslabones",
      posible_adaptacion_cadena: "RK 428MXZ4 124 eslabones",
      corona_trasera: "38T acero",
      posible_adaptacion_corona_trasera: "JT Sprockets JTR1223.38",
      tensor_ajustadores_cadena: "Original",
      posible_adaptacion_tensor_ajustadores_cadena: "—",
      tanque_combustible: "13.7 litros acero",
      posible_adaptacion_tanque_combustible: "—",
      tapa_tanque: "Original con llave",
      posible_adaptacion_tapa_tanque: "—",
      llave_combustible: "Vacío/Reserva/Off",
      posible_adaptacion_llave_combustible: "Llave universal Pingel",
      bomba_gasolina: "",
      posible_adaptacion_bomba_gasolina: "",
      filtro_combustible: "Inline original",
      posible_adaptacion_filtro_combustible: "K&N KF-1011 inline",
      carburador_inyector: "Keihin CV 26mm",
      posible_adaptacion_carburador_inyector: "Keihin FCR 28mm upgrade",
      cuerpo_aceleracion: "26mm",
      posible_adaptacion_cuerpo_aceleracion: "—",
      mangueras_combustible: "Original caucho",
      posible_adaptacion_mangueras_combustible: "Kit mangueras Gates",
      regulador_presion: "",
      posible_adaptacion_regulador_presion: "",
      inyectores: "",
      posible_adaptacion_inyectores: "",
      flotador_sensor_nivel: "Flotador original",
      posible_adaptacion_flotador_sensor_nivel: "—",
      filtro_aire: "Esponja original",
      posible_adaptacion_filtro_aire: "K&N RU-0960 pod filter",
      caja_filtro_aire: "Original plástico",
      posible_adaptacion_caja_filtro_aire: "Caja universal modificada",
      conductos_admision: "Original",
      posible_adaptacion_conductos_admision: "—",
      multiple_admision: "Original aluminio",
      posible_adaptacion_multiple_admision: "—",
      escape: "Original Honda cromado",
      posible_adaptacion_escape: "Arrow Universal 50mm compatible",
      multiple_escape: "Original",
      posible_adaptacion_multiple_escape: "—",
      silenciador: "Original cromado",
      posible_adaptacion_silenciador: "Arrow Road-Tech silencer",
      catalizador: "",
      posible_adaptacion_catalizador: "",
      sensor_oxigeno: "",
      posible_adaptacion_sensor_oxigeno: "",
      radiador: "",
      posible_adaptacion_radiador: "",
      ventilador: "",
      posible_adaptacion_ventilador: "",
      bomba_agua: "",
      posible_adaptacion_bomba_agua: "",
      mangueras_refrigeracion: "",
      posible_adaptacion_mangueras_refrigeracion: "",
      termostato: "",
      posible_adaptacion_termostato: "",
      deposito_refrigerante: "",
      posible_adaptacion_deposito_refrigerante: "",
      sensor_temperatura: "",
      posible_adaptacion_sensor_temperatura: "",
      aletas_refrigeracion: "Aletas fundidas cilindro",
      posible_adaptacion_aletas_refrigeracion: "—",
      conductos_deflectores_aire: "Original",
      posible_adaptacion_conductos_deflectores_aire: "—",
      rin_delantero: "17\" acero original",
      posible_adaptacion_rin_delantero: "Excel Takasago 17\"",
      neumatico_delantero: "IRC NR73 80/100-17",
      posible_adaptacion_neumatico_delantero: "Michelin Pilot Street 100/80-17",
      camara_delantera: "IRC",
      posible_adaptacion_camara_delantera: "Michelin equivalente",
      eje_delantero: "Original 12mm",
      posible_adaptacion_eje_delantero: "—",
      rodamientos_delanteros: "NSK 6301-2RS",
      posible_adaptacion_rodamientos_delanteros: "SKF 6301-2RS",
      disco_freno_delantero: "240mm single original",
      posible_adaptacion_disco_freno_delantero: "Galfer DF007 240mm",
      rin_trasero: "17\" acero original",
      posible_adaptacion_rin_trasero: "Excel Takasago 17\"",
      neumatico_trasero: "IRC NR73 100/80-17",
      posible_adaptacion_neumatico_trasero: "Michelin Pilot Street 120/70-17",
      camara_trasera: "IRC",
      posible_adaptacion_camara_trasera: "Michelin equivalente",
      eje_trasero: "Original 20mm",
      posible_adaptacion_eje_trasero: "—",
      rodamientos_traseros: "NSK 6302-2RS",
      posible_adaptacion_rodamientos_traseros: "SKF 6302-2RS",
      corona: "38T acero",
      posible_adaptacion_corona: "JT Sprockets JTR1223.38",
      disco_freno_trasero: "",
      posible_adaptacion_disco_freno_trasero: "",
      tambor_freno_trasero: "Tambor 130mm",
      posible_adaptacion_tambor_freno_trasero: "—",
      maneta_freno: "Original Honda",
      posible_adaptacion_maneta_freno: "Progrip 880 ajustable",
      bomba_freno: "Original Nissin delantera",
      posible_adaptacion_bomba_freno: "Brembo PS 13",
      deposito_liquido_freno: "Original",
      posible_adaptacion_deposito_liquido_freno: "Brembo externo",
      latiguillo_manguera_freno: "Original",
      posible_adaptacion_latiguillo_manguera_freno: "Galfer acero trenzado Honda",
      pinza_freno: "Nissin 2 pistones",
      posible_adaptacion_pinza_freno: "Brembo P2 34",
      pastillas_freno: "Sinterizadas OEM",
      posible_adaptacion_pastillas_freno: "EBC FA69HH sinterizadas",
      disco_freno: "240mm",
      posible_adaptacion_disco_freno: "Galfer DF007",
      tambor: "130mm trasero",
      posible_adaptacion_tambor: "—",
      zapatas: "Original Honda",
      posible_adaptacion_zapatas: "EBC 805 organicas",
      chasis_bastidor: "Doble cuna acero",
      posible_adaptacion_chasis_bastidor: "—",
      subchasis: "Acero original",
      posible_adaptacion_subchasis: "—",
      basculante: "Acero original",
      posible_adaptacion_basculante: "—",
      amortiguador_trasero: "Doble amortiguador",
      posible_adaptacion_amortiguador_trasero: "YSS G-series 340mm",
      horquilla_delantera: "Telescópica 33mm convencional",
      posible_adaptacion_horquilla_delantera: "—",
      barras_horquilla: "Original 33mm",
      posible_adaptacion_barras_horquilla: "—",
      botellas_horquilla: "Original",
      posible_adaptacion_botellas_horquilla: "—",
      resortes_horquilla: "Original",
      posible_adaptacion_resortes_horquilla: "Hyperpro RSC33-0095",
      tijas_superior_inferior: "Acero original",
      posible_adaptacion_tijas_superior_inferior: "—",
      rodamientos_direccion: "SKF 30204",
      posible_adaptacion_rodamientos_direccion: "FAG 30204-A",
      eje_direccion: "Original",
      posible_adaptacion_eje_direccion: "—",
      manillar: "Tubo acero 22mm",
      posible_adaptacion_manillar: "Renthal 7/8\" Street series",
      punos: "Original Honda",
      posible_adaptacion_punos: "Progrip 714 22mm",
      acelerador: "Cable push-pull",
      posible_adaptacion_acelerador: "Domino kit universal",
      cable_sensor_acelerador: "Cable original 90cm",
      posible_adaptacion_cable_sensor_acelerador: "Cable Venhill",
      maneta_embrague: "Original Honda",
      posible_adaptacion_maneta_embrague: "Progrip 880",
      maneta_freno_control: "Original Honda",
      posible_adaptacion_maneta_freno_control: "Progrip 880",
      pedal_cambio: "Acero original",
      posible_adaptacion_pedal_cambio: "CNC aluminio universal",
      pedal_freno: "Original",
      posible_adaptacion_pedal_freno: "—",
      estriberas: "Acero original",
      posible_adaptacion_estriberas: "Aluminio CNC universal",
      soporte_estriberas: "Original",
      posible_adaptacion_soporte_estriberas: "—",
      caballete_lateral: "Acero original",
      posible_adaptacion_caballete_lateral: "—",
      caballete_central: "Acero original",
      posible_adaptacion_caballete_central: "—",
      bateria: "Yuasa YTX7L-BS 12V 6Ah",
      posible_adaptacion_bateria: "Motobatt MBTX7U",
      alternador_estator: "Original 100W",
      posible_adaptacion_alternador_estator: "—",
      rotor_volante_magnetico: "Original",
      posible_adaptacion_rotor_volante_magnetico: "—",
      regulador_rectificador: "Original Honda",
      posible_adaptacion_regulador_rectificador: "Moose Racing Honda compatible",
      motor_arranque: "Original Honda 0.4kW",
      posible_adaptacion_motor_arranque: "—",
      rele_arranque: "Original",
      posible_adaptacion_rele_arranque: "Relé universal 30A",
      solenoide: "Original",
      posible_adaptacion_solenoide: "—",
      ecu_cdi: "CDI Digital Honda",
      posible_adaptacion_ecu_cdi: "CDI Dynatek D35-5026",
      bobina_encendido: "Original",
      posible_adaptacion_bobina_encendido: "Dyna DC6-1",
      bujia: "NGK CPR8EA-9",
      posible_adaptacion_bujia: "NGK BCPR8EIX iridio",
      cableado: "Original Honda",
      posible_adaptacion_cableado: "—",
      fusibles: "Original 10A/15A",
      posible_adaptacion_fusibles: "Kit ATC universales",
      reles: "Original",
      posible_adaptacion_reles: "—",
      interruptor_encendido: "Original",
      posible_adaptacion_interruptor_encendido: "—",
      interruptor_luces: "Original",
      posible_adaptacion_interruptor_luces: "—",
      interruptor_intermitentes: "Original",
      posible_adaptacion_interruptor_intermitentes: "—",
      claxon: "Original Honda",
      posible_adaptacion_claxon: "FIAMM HO2 120dB",
      sensores: "CKP original",
      posible_adaptacion_sensores: "—",
      faro_delantero: "Halógeno H4 35/35W",
      posible_adaptacion_faro_delantero: "Conversión LED H4 universal",
      luz_posicion: "5W incandescente",
      posible_adaptacion_luz_posicion: "LED T10 equivalente",
      luz_trasera: "10W incandescente",
      posible_adaptacion_luz_trasera: "LED bayoneta 1157 equiv",
      luz_freno: "21W incandescente",
      posible_adaptacion_luz_freno: "LED bayoneta 1157",
      intermitentes: "21W ámbar incandescente",
      posible_adaptacion_intermitentes: "LED Rizoma Freccia",
      bombillas_modulos_led: "",
      posible_adaptacion_bombillas_modulos_led: "",
      luz_matricula: "5W incandescente",
      posible_adaptacion_luz_matricula: "LED T10 equivalente",
      deposito_tanque: "13.7L acero",
      posible_adaptacion_deposito_tanque: "—",
      asiento: "Original monobloque",
      posible_adaptacion_asiento: "—",
      guardabarros_delantero: "Original plástico",
      posible_adaptacion_guardabarros_delantero: "—",
      guardabarros_trasero: "Original plástico",
      posible_adaptacion_guardabarros_trasero: "—",
      carenados: "",
      posible_adaptacion_carenados: "",
      paneles_laterales: "Original plástico",
      posible_adaptacion_paneles_laterales: "—",
      colin: "Original",
      posible_adaptacion_colin: "—",
      cupula_parabrisas: "",
      posible_adaptacion_cupula_parabrisas: "",
      parrilla_portaequipaje: "",
      posible_adaptacion_parrilla_portaequipaje: "Parrilla universal Honda",
      soporte_matricula: "Original",
      posible_adaptacion_soporte_matricula: "Eliminador Evotech",
      velocimetro: "Analógico original",
      posible_adaptacion_velocimetro: "Koso GP-Style digital",
      tacometro: "",
      posible_adaptacion_tacometro: "Koso digital universal",
      odometro: "Mecánico integrado",
      posible_adaptacion_odometro: "—",
      indicador_combustible: "Llave manual",
      posible_adaptacion_indicador_combustible: "Sensor Koso universal",
      indicador_temperatura: "",
      posible_adaptacion_indicador_temperatura: "",
      pantalla_panel_instrumentos: "Analógico",
      posible_adaptacion_pantalla_panel_instrumentos: "Koso RX2N+ digital",
      testigo_aceite: "Original",
      posible_adaptacion_testigo_aceite: "—",
      testigo_motor: "",
      posible_adaptacion_testigo_motor: "",
      testigo_direccionales: "Original",
      posible_adaptacion_testigo_direccionales: "—",
      testigo_luces_altas: "Original",
      posible_adaptacion_testigo_luces_altas: "—",
      testigo_neutro: "Original",
      posible_adaptacion_testigo_neutro: "—",
      tornillos: "Kit M6/M8 acero",
      posible_adaptacion_tornillos: "Kit inox M6/M8",
      tuercas: "Original",
      posible_adaptacion_tuercas: "Tuercas nyloc inox",
      arandelas: "Original",
      posible_adaptacion_arandelas: "—",
      pasadores: "Original",
      posible_adaptacion_pasadores: "—",
      clips: "Original",
      posible_adaptacion_clips: "—",
      seguros: "Original",
      posible_adaptacion_seguros: "—",
      abrazaderas: "Original",
      posible_adaptacion_abrazaderas: "Abrazaderas inox",
      retenes: "Original 33mm horquilla",
      posible_adaptacion_retenes: "Athena 33mm",
      juntas: "Kit juntas OEM",
      posible_adaptacion_juntas: "Athena kit completo Honda",
      o_rings: "Original NBR",
      posible_adaptacion_o_rings: "Viton equivalente",
      rodamientos: "NSK varios",
      posible_adaptacion_rodamientos: "SKF equivalentes",
      bujes: "Original",
      posible_adaptacion_bujes: "DU bronze",
      resortes: "Original",
      posible_adaptacion_resortes: "—",
      cables: "Kit OEM Honda",
      posible_adaptacion_cables: "Venhill kit Honda CB",
      mangueras: "Original caucho",
      posible_adaptacion_mangueras: "Kit silicona Samco",
    },
  ];

  save("motoparts_clientes", clientes);
  save("motoparts_motos", motos);
  save("motoparts_recomendado", recomendados);
  localStorage.setItem(SEED_KEY, "1");
}

// ─── Clientes ──────────────────────────────────────────────────────────────────

export const clientesDB = {
  getAll(): Cliente[] {
    if (desktopApi) return desktopRequest<Cliente[]>("getAll", { entity: "clientes" });
    seed();
    return load<Cliente>("motoparts_clientes");
  },
  getById(id: number): Cliente | undefined {
    if (desktopApi) return desktopRequest<Cliente | null>("getById", { entity: "clientes", id }) ?? undefined;
    return this.getAll().find((c) => c.id_cliente === id);
  },
  create(data: Omit<Cliente, "id_cliente">): Cliente {
    if (desktopApi) return desktopRequest<Cliente>("create", { entity: "clientes", data });
    const all = this.getAll();
    const nuevo: Cliente = { id_cliente: nextId(all as unknown as { [k: string]: unknown }[]), ...data };
    save("motoparts_clientes", [...all, nuevo]);
    return nuevo;
  },
  update(id: number, data: Partial<Omit<Cliente, "id_cliente">>): Cliente | null {
    if (desktopApi) return desktopRequest<Cliente | null>("update", { entity: "clientes", id, data });
    const all = this.getAll();
    const idx = all.findIndex((c) => c.id_cliente === id);
    if (idx === -1) return null;
    all[idx] = { ...all[idx], ...data };
    save("motoparts_clientes", all);
    return all[idx];
  },
  delete(id: number): boolean {
    if (desktopApi) return desktopRequest<boolean>("delete", { entity: "clientes", id });
    const all = this.getAll();
    const filtered = all.filter((c) => c.id_cliente !== id);
    if (filtered.length === all.length) return false;
    save("motoparts_clientes", filtered);
    // unlink motos
    const motos = load<Moto>("motoparts_motos").map((m) =>
      m.id_cliente === id ? { ...m, id_cliente: null } : m
    );
    save("motoparts_motos", motos);
    return true;
  },
};

// ─── Motos ─────────────────────────────────────────────────────────────────────

export const motosDB = {
  getAll(): Moto[] {
    if (desktopApi) return desktopRequest<Moto[]>("getAll", { entity: "motos" });
    seed();
    return load<Moto>("motoparts_motos");
  },
  getById(id: number): Moto | undefined {
    if (desktopApi) return desktopRequest<Moto | null>("getById", { entity: "motos", id }) ?? undefined;
    return this.getAll().find((m) => m.id_moto === id);
  },
  getByClienteId(clienteId: number): Moto | undefined {
    if (desktopApi) return desktopRequest<Moto | null>("getByClienteId", { id: clienteId }) ?? undefined;
    return this.getAll().find((m) => m.id_cliente === clienteId);
  },
  create(data: Omit<Moto, "id_moto">): Moto {
    if (desktopApi) return desktopRequest<Moto>("create", { entity: "motos", data });
    const all = this.getAll();
    const nueva: Moto = { id_moto: nextId(all as unknown as { [k: string]: unknown }[]), ...data };
    save("motoparts_motos", [...all, nueva]);
    return nueva;
  },
  update(id: number, data: Partial<Omit<Moto, "id_moto">>): Moto | null {
    if (desktopApi) return desktopRequest<Moto | null>("update", { entity: "motos", id, data });
    const all = this.getAll();
    const idx = all.findIndex((m) => m.id_moto === id);
    if (idx === -1) return null;
    all[idx] = { ...all[idx], ...data };
    save("motoparts_motos", all);
    return all[idx];
  },
  delete(id: number): boolean {
    if (desktopApi) return desktopRequest<boolean>("delete", { entity: "motos", id });
    const all = this.getAll();
    const filtered = all.filter((m) => m.id_moto !== id);
    if (filtered.length === all.length) return false;
    save("motoparts_motos", filtered);
    return true;
  },
};

// ─── Recomendado ───────────────────────────────────────────────────────────────

export const recomendadoDB = {
  getAll(): Recomendado[] {
    if (desktopApi) return desktopRequest<Recomendado[]>("getAll", { entity: "recomendado" });
    seed();
    return load<Recomendado>("motoparts_recomendado");
  },
  getById(id: number): Recomendado | undefined {
    if (desktopApi) return desktopRequest<Recomendado | null>("getById", { entity: "recomendado", id }) ?? undefined;
    return this.getAll().find((r) => r.id_recomendado === id);
  },
  search(marca: string, modelo: string): Recomendado[] {
    if (desktopApi) return desktopRequest<Recomendado[]>("search", { marca, modelo });
    const q = (s: string) => s.toLowerCase().trim();
    return this.getAll().filter(
      (r) =>
        (!marca || q(r.marca).includes(q(marca))) &&
        (!modelo || q(r.modelo).includes(q(modelo)))
    );
  },
  create(data: Omit<Recomendado, "id_recomendado">): Recomendado {
    if (desktopApi) return desktopRequest<Recomendado>("create", { entity: "recomendado", data });
    const all = this.getAll();
    const nuevo = { id_recomendado: nextId(all as unknown as { [k: string]: unknown }[]), ...data } as Recomendado;
    save("motoparts_recomendado", [...all, nuevo]);
    return nuevo;
  },
  update(id: number, data: Partial<Omit<Recomendado, "id_recomendado">>): Recomendado | null {
    if (desktopApi) return desktopRequest<Recomendado | null>("update", { entity: "recomendado", id, data });
    const all = this.getAll();
    const idx = all.findIndex((r) => r.id_recomendado === id);
    if (idx === -1) return null;
    all[idx] = { ...all[idx], ...data };
    save("motoparts_recomendado", all);
    return all[idx];
  },
  delete(id: number): boolean {
    if (desktopApi) return desktopRequest<boolean>("delete", { entity: "recomendado", id });
    const all = this.getAll();
    const filtered = all.filter((r) => r.id_recomendado !== id);
    if (filtered.length === all.length) return false;
    save("motoparts_recomendado", filtered);
    return true;
  },
};

export const galeraDB = {
  getAll(): Galera[] {
    if (desktopApi) return desktopRequest<Galera[]>("getAll", { entity: "galera" });
    try {
      return JSON.parse(localStorage.getItem("motoparts_galera") || "[]") as Galera[];
    } catch {
      return [];
    }
  },
  create(data: Omit<Galera, "id_galera">): Galera {
    if (desktopApi) return desktopRequest<Galera>("create", { entity: "galera", data });
    const all = this.getAll();
    const record = { id_galera: nextId(all as unknown as { [k: string]: unknown }[]), ...data };
    localStorage.setItem("motoparts_galera", JSON.stringify([...all, record]));
    return record;
  },
  update(id: number, data: Partial<Omit<Galera, "id_galera">>): Galera | null {
    if (desktopApi) return desktopRequest<Galera | null>("update", { entity: "galera", id, data });
    const all = this.getAll();
    const index = all.findIndex((record) => record.id_galera === id);
    if (index === -1) return null;
    all[index] = { ...all[index], ...data };
    localStorage.setItem("motoparts_galera", JSON.stringify(all));
    return all[index];
  },
  delete(id: number): boolean {
    if (desktopApi) return desktopRequest<boolean>("delete", { entity: "galera", id });
    const all = this.getAll();
    const filtered = all.filter((record) => record.id_galera !== id);
    localStorage.setItem("motoparts_galera", JSON.stringify(filtered));
    return filtered.length !== all.length;
  },
};
